/**
 * Regenerate migrations/0004_better_auth.sql from the EXACT pinned better-auth
 * version. Run after bumping better-auth. test/auth.schema.test.ts fails if this
 * file and the pinned version disagree.
 *
 *   pnpm exec tsx scripts/auth/generate-schema.ts
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { pathToFileURL } from "node:url";

import Database from "better-sqlite3";
import { betterAuth } from "better-auth";
import { getMigrations } from "better-auth/db/migration";

import { buildAuthOptions, PINNED_BETTER_AUTH_VERSION } from "../../app/lib/authOptions";

const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "migrations",
  "0004_better_auth.sql",
);

export async function generateAuthMigrationSql(): Promise<string> {
  const auth = betterAuth(
    buildAuthOptions({
      database: new Database(":memory:") as never,
      secret: "x".repeat(48),
      baseURL: "http://localhost:8787",
    }),
  );
  const { compileMigrations } = await getMigrations(auth.options);
  const body = (await compileMigrations()).trim();
  return (
    `-- GENERATED by scripts/auth/generate-schema.ts from better-auth@${PINNED_BETTER_AUTH_VERSION}.\n` +
    `-- Do NOT edit by hand. Regenerate after bumping better-auth; the drift test\n` +
    `-- (test/auth.schema.test.ts) fails if this file and the pinned version disagree.\n\n` +
    body +
    "\n"
  );
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const sql = await generateAuthMigrationSql();
  writeFileSync(OUT, sql);
  console.log(`Wrote ${OUT}`);
}
