/**
 * Dev tool. Reads fixtures/hvac/* and writes scripts/seed.sql, which
 * `pnpm db:seed:local` feeds to `wrangler d1 execute --local`.
 *
 *   pnpm seed:generate
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { ClientSchema, CoverageSchema, ServiceSchema } from "../src/core/schema";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const hvac = join(root, "fixtures", "hvac");

const readJson = (p: string): unknown => JSON.parse(readFileSync(p, "utf8"));
const q = (v: string): string => `'${v.replace(/'/g, "''")}'`;
const now = "2026-08-30T00:00:00.000Z";

const services = (readJson(join(hvac, "catalog.json")) as unknown[]).map((s) =>
  ServiceSchema.parse(s),
);
const client = ClientSchema.parse(readJson(join(hvac, "client.json")));
const coverage = (readJson(join(hvac, "coverage.none.json")) as unknown[]).map((c) =>
  CoverageSchema.parse(c),
);

const lines: string[] = [
  "-- Generated by scripts/generate-seed.ts. Do not edit by hand.",
  "DELETE FROM opportunities;",
  "DELETE FROM evidence_bundles;",
  "DELETE FROM client_coverage;",
  "DELETE FROM clients;",
  "DELETE FROM services;",
  "",
];

for (const s of services) {
  lines.push(
    `INSERT INTO services (id, name, description, price_min, price_max, tags, active, updated_at) VALUES (` +
      `${q(s.id)}, ${q(s.name)}, ${q(s.description)}, ${s.priceMin}, ${s.priceMax}, ` +
      `${q(JSON.stringify(s.tags))}, ${s.active ? 1 : 0}, ${q(now)});`,
  );
}
lines.push("");
lines.push(
  `INSERT INTO clients (id, name, domain, offerings, notes, updated_at) VALUES (` +
    `${q(client.id)}, ${q(client.name)}, ${q(client.domain)}, ${q(JSON.stringify(client.offerings))}, ` +
    `${q(client.notes)}, ${q(now)});`,
);
lines.push("");
for (const c of coverage) {
  lines.push(
    `INSERT INTO client_coverage (client_id, service_id, note) VALUES (` +
      `${q(c.clientId)}, ${q(c.serviceId)}, ${c.note ? q(c.note) : "NULL"});`,
  );
}
lines.push("");

writeFileSync(join(root, "scripts", "seed.sql"), lines.join("\n"));
console.log(`Wrote scripts/seed.sql (${services.length} services, 1 client, ${coverage.length} coverage rows)`);
