/**
 * Dev tool. Reads fixtures/hvac/* and writes scripts/seed.sql, which
 * `pnpm db:seed:local` feeds to `wrangler d1 execute --local`.
 *
 * The demo data goes ONLY into the demo workspace (ws_demo, created by migration
 * 0005). Real signups never touch it.
 *
 *   pnpm seed:generate
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { ClientSchema, CoverageSchema, ServiceSchema } from "../src/core/schema";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const hvac = join(root, "fixtures", "hvac");

const readJson = (p: string): unknown => JSON.parse(readFileSync(p, "utf8"));
const q = (v: string): string => `'${v.replace(/'/g, "''")}'`;
const now = "2026-08-30T00:00:00.000Z";
const WS = "ws_demo";

const services = (readJson(join(hvac, "catalog.json")) as unknown[]).map((s) => ServiceSchema.parse(s));
const client = ClientSchema.parse(readJson(join(hvac, "client.json")));
const coverage = (readJson(join(hvac, "coverage.none.json")) as unknown[]).map((c) =>
  CoverageSchema.parse(c),
);

const lines: string[] = [
  "-- Generated by scripts/generate-seed.ts. Do not edit by hand.",
  "-- Demo data for the demo workspace only. Real workspaces are never seeded.",
  "",
  `INSERT OR IGNORE INTO user (id, name, email, "emailVerified", "createdAt", "updatedAt") VALUES (`,
  `  'user_demo', 'Demo', 'demo@clientgrowth.local', 1, ${q(now)}, ${q(now)});`,
  `INSERT OR IGNORE INTO workspaces (id, name, owner_user_id, created_at) VALUES ('${WS}', 'Demo Agency', 'user_demo', ${q(now)});`,
  `INSERT OR IGNORE INTO workspace_members (workspace_id, user_id, role, created_at) VALUES ('${WS}', 'user_demo', 'owner', ${q(now)});`,
  "",
  `DELETE FROM opportunities WHERE workspace_id = '${WS}';`,
  `DELETE FROM evidence_bundles WHERE workspace_id = '${WS}';`,
  `DELETE FROM client_coverage WHERE workspace_id = '${WS}';`,
  `DELETE FROM clients WHERE workspace_id = '${WS}';`,
  `DELETE FROM services WHERE workspace_id = '${WS}';`,
  "",
];

for (const s of services) {
  lines.push(
    `INSERT INTO services (id, workspace_id, name, description, price_min, price_max, tags, active, updated_at) VALUES (` +
      `${q(s.id)}, '${WS}', ${q(s.name)}, ${q(s.description)}, ${s.priceMin}, ${s.priceMax}, ` +
      `${q(JSON.stringify(s.tags))}, ${s.active ? 1 : 0}, ${q(now)});`,
  );
}
lines.push("");
lines.push(
  `INSERT INTO clients (id, workspace_id, name, domain, offerings, notes, updated_at) VALUES (` +
    `${q(client.id)}, '${WS}', ${q(client.name)}, ${q(client.domain)}, ${q(JSON.stringify(client.offerings))}, ` +
    `${q(client.notes)}, ${q(now)});`,
);
lines.push("");
for (const c of coverage) {
  lines.push(
    `INSERT INTO client_coverage (workspace_id, client_id, service_id, note) VALUES (` +
      `'${WS}', ${q(c.clientId)}, ${q(c.serviceId)}, ${c.note ? q(c.note) : "NULL"});`,
  );
}
lines.push("");

writeFileSync(join(root, "scripts", "seed.sql"), lines.join("\n"));
console.log(
  `Wrote scripts/seed.sql (${services.length} services, 1 client, ${coverage.length} coverage rows in ${WS})`,
);
