-- Generated by scripts/generate-seed.ts. Do not edit by hand.
DELETE FROM opportunities;
DELETE FROM evidence_bundles;
DELETE FROM client_coverage;
DELETE FROM clients;
DELETE FROM services;

INSERT INTO services (id, name, description, price_min, price_max, tags, active, updated_at) VALUES ('svc-landing-page', 'Service Landing Page', 'Design and build a dedicated, conversion-focused landing page for a single service line: copy, on-page SEO, and a primary lead-capture call to action.', 900, 1500, '["landing-page"]', 1, '2026-08-30T00:00:00.000Z');
INSERT INTO services (id, name, description, price_min, price_max, tags, active, updated_at) VALUES ('svc-seo-retainer', 'Monthly SEO Retainer', 'Ongoing technical and content SEO work billed monthly.', 800, 2500, '["seo","retainer"]', 1, '2026-08-30T00:00:00.000Z');
INSERT INTO services (id, name, description, price_min, price_max, tags, active, updated_at) VALUES ('svc-brand-refresh', 'Brand Refresh', 'Visual identity refresh: logo, palette, typography, brand guidelines.', 2500, 6000, '["brand"]', 1, '2026-08-30T00:00:00.000Z');
INSERT INTO services (id, name, description, price_min, price_max, tags, active, updated_at) VALUES ('svc-conversion-fix', 'Conversion Path Fix', 'Diagnose and repair a broken conversion element (dead CTA, broken form submission, unusable click-to-call link) so the client stops losing leads.', 300, 900, '["conversion-fix"]', 1, '2026-08-30T00:00:00.000Z');

INSERT INTO clients (id, name, domain, offerings, notes, updated_at) VALUES ('client-coolbreeze', 'Cool Breeze HVAC', 'coolbreezehvac.example', '["heat pump installation","air conditioning repair","furnace installation","duct cleaning"]', 'Denver residential HVAC. Owner wants more high-ticket install work.', '2026-08-30T00:00:00.000Z');

