-- Generated by scripts/generate-seed.ts. Do not edit by hand.
-- Demo data for the demo workspace only. Real workspaces are never seeded.

INSERT OR IGNORE INTO user (id, name, email, "emailVerified", "createdAt", "updatedAt") VALUES (
  'user_demo', 'Demo', 'demo@clientgrowth.local', 1, '2026-08-30T00:00:00.000Z', '2026-08-30T00:00:00.000Z');
INSERT OR IGNORE INTO workspaces (id, name, owner_user_id, created_at) VALUES ('ws_demo', 'Demo Agency', 'user_demo', '2026-08-30T00:00:00.000Z');
INSERT OR IGNORE INTO workspace_members (workspace_id, user_id, role, created_at) VALUES ('ws_demo', 'user_demo', 'owner', '2026-08-30T00:00:00.000Z');

DELETE FROM opportunities WHERE workspace_id = 'ws_demo';
DELETE FROM evidence_bundles WHERE workspace_id = 'ws_demo';
DELETE FROM client_coverage WHERE workspace_id = 'ws_demo';
DELETE FROM clients WHERE workspace_id = 'ws_demo';
DELETE FROM services WHERE workspace_id = 'ws_demo';

INSERT INTO services (id, workspace_id, name, description, price_min, price_max, tags, active, updated_at) VALUES ('svc-landing-page', 'ws_demo', 'Service Landing Page', 'Design and build a dedicated, conversion-focused landing page for a single service line: copy, on-page SEO, and a primary lead-capture call to action.', 900, 1500, '["landing-page"]', 1, '2026-08-30T00:00:00.000Z');
INSERT INTO services (id, workspace_id, name, description, price_min, price_max, tags, active, updated_at) VALUES ('svc-seo-retainer', 'ws_demo', 'Monthly SEO Retainer', 'Ongoing technical and content SEO work billed monthly.', 800, 2500, '["seo","retainer"]', 1, '2026-08-30T00:00:00.000Z');
INSERT INTO services (id, workspace_id, name, description, price_min, price_max, tags, active, updated_at) VALUES ('svc-brand-refresh', 'ws_demo', 'Brand Refresh', 'Visual identity refresh: logo, palette, typography, brand guidelines.', 2500, 6000, '["brand"]', 1, '2026-08-30T00:00:00.000Z');
INSERT INTO services (id, workspace_id, name, description, price_min, price_max, tags, active, updated_at) VALUES ('svc-conversion-fix', 'ws_demo', 'Conversion Path Fix', 'Diagnose and repair a broken conversion element (dead CTA, broken form submission, unusable click-to-call link) so the client stops losing leads.', 300, 900, '["conversion-fix"]', 1, '2026-08-30T00:00:00.000Z');

INSERT INTO clients (id, workspace_id, name, domain, offerings, notes, updated_at) VALUES ('client-coolbreeze', 'ws_demo', 'Cool Breeze HVAC', 'coolbreezehvac.example', '["heat pump installation","air conditioning repair","furnace installation","duct cleaning"]', 'Denver residential HVAC. Owner wants more high-ticket install work.', '2026-08-30T00:00:00.000Z');

