import { createRequestHandler, type ServerBuild } from "react-router";

import { parseEnv } from "@/config/env";
import { d1Db } from "../app/lib/d1.server";
import { runMonitoringTick } from "../app/lib/monitoring.server";
import { runMonitorDigestTick } from "../app/lib/monitorDigest.server";
import { runWithWorkerExecutionContext } from "../app/lib/workerContext.server";

/**
 * The daily cron that drives the MONITOR weekly digest. It runs every day and
 * emails only the workspaces whose weekly digest has actually come due, so it is
 * deliberately not tied to the hourly scan. Must match wrangler.jsonc.
 */
const MONITOR_DIGEST_CRON = "0 13 * * *";

/**
 * Cloudflare Worker entry. The domain engine in `src/` never imports this file.
 *
 * `../build/server` is produced by `react-router build`. Wrangler bundles this
 * entry and serves `build/client` as static assets, falling through to here for
 * everything else.
 */
declare global {
  interface CloudflareEnvironment {
    DB: D1Database;
    /** Better Auth: signing secret (>= 32 chars). `wrangler secret put`. */
    BETTER_AUTH_SECRET?: string;
    /** Better Auth: explicit trusted base URL (never derived from Host/Origin). */
    BETTER_AUTH_URL?: string;
    RESEND_API_KEY?: string;
    RESEND_FROM_EMAIL?: string;
    AI_PROVIDER?: string;
    DEEPSEEK_API_KEY?: string;
    DEEPSEEK_BASE_URL?: string;
    DEEPSEEK_MODEL?: string;
    MAX_AI_CALLS_PER_RUN?: string;
    /** Clients one scheduled monitoring tick may analyze. */
    MONITORING_MAX_CLIENTS_PER_RUN?: string;
    /**
     * Operator-only trigger for the scheduled monitoring path. Absent (the
     * default) means the trigger route does not exist at all.
     * `wrangler secret put`.
     */
    MONITORING_TRIGGER_TOKEN?: string;
    /** Who has the paid MONITOR feature. See src/core/entitlements.ts. */
    MONITOR_ENTITLEMENT_MODE?: string;
    MONITOR_ALLOWLIST?: string;
    /** Workspaces one digest tick may email. */
    MONITOR_DIGEST_MAX_PER_RUN?: string;
    /** Operator-only trigger for the digest tick. Absent => the route 404s. */
    MONITOR_DIGEST_TRIGGER_TOKEN?: string;
  }
}

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error - generated by `react-router build`; absent until the first build
import * as build from "../build/server/index.js";

const handler = createRequestHandler(build as unknown as ServerBuild, "production");

export default {
  fetch(request: Request, env: CloudflareEnvironment, ctx: ExecutionContext) {
    return runWithWorkerExecutionContext(ctx, () =>
      handler(request, { cloudflare: { env, ctx } }),
    );
  },

  /**
   * Recurring monitoring. One cron trigger for the whole product, not one per
   * client: this fires on a fixed schedule and each tick asks the database which
   * monitored clients are actually due, then processes a bounded batch of them.
   *
   * The scheduler's frequency and a client's cadence are independent. An hourly
   * tick can serve weekly clients precisely because being due, not being ticked,
   * is what selects a client.
   *
   * `waitUntil` keeps the invocation alive for the whole tick; the tick's own
   * wall-clock budget is what actually ends it, well inside the platform limit.
   *
   * This is the one path nobody is watching while it runs, so it must never fail
   * quietly. A tick that throws before its own error handling — a bad binding, a
   * D1 outage, a malformed env — used to reject straight out of this handler and
   * leave no log line at all: the hour simply produced nothing. Now the failure
   * is logged in the same shape as a success and then rethrown, so it also lands
   * in the platform's own cron error rate where an alert can reach a human.
   */
  async scheduled(controller: ScheduledController, env: CloudflareEnvironment, ctx: ExecutionContext) {
    const rawEnv = env as unknown as Record<string, unknown>;

    // Which unattended job fired is decided by the cron, not by a second
    // handler. The digest tick spends nothing at the provider; the monitoring
    // tick does, which is why they are separate schedules.
    if (controller.cron === MONITOR_DIGEST_CRON) {
      await runScheduledTick(
        ctx,
        "monitor-digest",
        () => runMonitorDigestTick({ db: d1Db(env.DB as never), env: rawEnv }),
        (r) =>
          `considered=${r.considered} sent=${r.sent} skipped=${r.skipped} failed=${r.failed}`,
      );
      return;
    }

    await runScheduledTick(
      ctx,
      "monitoring",
      () =>
        runMonitoringTick({
          db: d1Db(env.DB as never),
          env: rawEnv,
          limit: parseEnv(rawEnv).MONITORING_MAX_CLIENTS_PER_RUN,
        }),
      (r) =>
        `considered=${r.considered} scanned=${r.scanned} skipped=${r.skipped} ` +
        `failed=${r.failed} new=${r.newFindings} resolved=${r.resolvedFindings} ` +
        `evaluatorCalls=${r.evaluatorCalls} budgetExhausted=${r.budgetExhausted}`,
    );
  },
} satisfies ExportedHandler<CloudflareEnvironment>;

/**
 * Run one scheduled tick with the safety discipline every unattended path here
 * shares: keep the invocation alive with `waitUntil`, log a one-line summary on
 * success, and — crucially — **rethrow** a pre-reporting failure so it lands in
 * Cloudflare's cron error rate where an alert can reach a human. A tick that
 * fails silently is an hour that produced nothing and told no one.
 */
async function runScheduledTick<T>(
  ctx: ExecutionContext,
  label: string,
  run: () => Promise<T>,
  summary: (result: T) => string,
): Promise<void> {
  const task = runWithWorkerExecutionContext(ctx, run);
  // The rejection is handled below; this copy only keeps the invocation alive,
  // so it is silenced to avoid reporting the same failure twice.
  ctx.waitUntil(task.catch(() => undefined));

  let result: T;
  try {
    result = await task;
  } catch (error) {
    const cause = error instanceof Error ? `${error.name}: ${error.message}` : String(error);
    console.error(`[${label}] tick failed before reporting: ${cause}`);
    throw error;
  }

  console.log(`[${label}] ${summary(result)}`);
}
