import { createRequestHandler, type ServerBuild } from "react-router";

import { parseEnv } from "@/config/env";
import { d1Db } from "../app/lib/d1.server";
import { runMonitoringTick } from "../app/lib/monitoring.server";
import { runWithWorkerExecutionContext } from "../app/lib/workerContext.server";

/**
 * Cloudflare Worker entry. The domain engine in `src/` never imports this file.
 *
 * `../build/server` is produced by `react-router build`. Wrangler bundles this
 * entry and serves `build/client` as static assets, falling through to here for
 * everything else.
 */
declare global {
  interface CloudflareEnvironment {
    DB: D1Database;
    /** Better Auth: signing secret (>= 32 chars). `wrangler secret put`. */
    BETTER_AUTH_SECRET?: string;
    /** Better Auth: explicit trusted base URL (never derived from Host/Origin). */
    BETTER_AUTH_URL?: string;
    RESEND_API_KEY?: string;
    RESEND_FROM_EMAIL?: string;
    AI_PROVIDER?: string;
    DEEPSEEK_API_KEY?: string;
    DEEPSEEK_BASE_URL?: string;
    DEEPSEEK_MODEL?: string;
    MAX_AI_CALLS_PER_RUN?: string;
    /** Clients one scheduled monitoring tick may analyze. */
    MONITORING_MAX_CLIENTS_PER_RUN?: string;
    /**
     * Operator-only trigger for the scheduled monitoring path. Absent (the
     * default) means the trigger route does not exist at all.
     * `wrangler secret put`.
     */
    MONITORING_TRIGGER_TOKEN?: string;
  }
}

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error - generated by `react-router build`; absent until the first build
import * as build from "../build/server/index.js";

const handler = createRequestHandler(build as unknown as ServerBuild, "production");

export default {
  fetch(request: Request, env: CloudflareEnvironment, ctx: ExecutionContext) {
    return runWithWorkerExecutionContext(ctx, () =>
      handler(request, { cloudflare: { env, ctx } }),
    );
  },

  /**
   * Recurring monitoring. One cron trigger for the whole product, not one per
   * client: this fires on a fixed schedule and each tick asks the database which
   * monitored clients are actually due, then processes a bounded batch of them.
   *
   * The scheduler's frequency and a client's cadence are independent. An hourly
   * tick can serve weekly clients precisely because being due, not being ticked,
   * is what selects a client.
   *
   * `waitUntil` keeps the invocation alive for the whole tick; the tick's own
   * wall-clock budget is what actually ends it, well inside the platform limit.
   */
  async scheduled(_controller: ScheduledController, env: CloudflareEnvironment, ctx: ExecutionContext) {
    const tick = runWithWorkerExecutionContext(ctx, () =>
      runMonitoringTick({
        db: d1Db(env.DB as never),
        env: env as unknown as Record<string, unknown>,
        limit: parseEnv(env as unknown as Record<string, unknown>).MONITORING_MAX_CLIENTS_PER_RUN,
      }),
    );
    ctx.waitUntil(tick);
    const result = await tick;
    console.log(
      `[monitoring] considered=${result.considered} scanned=${result.scanned} ` +
        `skipped=${result.skipped} failed=${result.failed} new=${result.newFindings} ` +
        `resolved=${result.resolvedFindings} evaluatorCalls=${result.evaluatorCalls} ` +
        `budgetExhausted=${result.budgetExhausted}`,
    );
  },
} satisfies ExportedHandler<CloudflareEnvironment>;
