import { createRequestHandler, type ServerBuild } from "react-router";

import { runWithWorkerExecutionContext } from "../app/lib/workerContext.server";

/**
 * Cloudflare Worker entry. The domain engine in `src/` never imports this file.
 *
 * `../build/server` is produced by `react-router build`. Wrangler bundles this
 * entry and serves `build/client` as static assets, falling through to here for
 * everything else.
 */
declare global {
  interface CloudflareEnvironment {
    DB: D1Database;
    /** Better Auth: signing secret (>= 32 chars). `wrangler secret put`. */
    BETTER_AUTH_SECRET?: string;
    /** Better Auth: explicit trusted base URL (never derived from Host/Origin). */
    BETTER_AUTH_URL?: string;
    RESEND_API_KEY?: string;
    RESEND_FROM_EMAIL?: string;
    AI_PROVIDER?: string;
    DEEPSEEK_API_KEY?: string;
    DEEPSEEK_BASE_URL?: string;
    DEEPSEEK_MODEL?: string;
    MAX_AI_CALLS_PER_RUN?: string;
  }
}

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error - generated by `react-router build`; absent until the first build
import * as build from "../build/server/index.js";

const handler = createRequestHandler(build as unknown as ServerBuild, "production");

export default {
  fetch(request: Request, env: CloudflareEnvironment, ctx: ExecutionContext) {
    return runWithWorkerExecutionContext(ctx, () =>
      handler(request, { cloudflare: { env, ctx } }),
    );
  },
} satisfies ExportedHandler<CloudflareEnvironment>;
